---
- name: Copy postgres-backup executable
  ansible.builtin.template:
    src: postgres-backup.j2
    dest: /usr/local/bin/postgres-backup
    owner: postgres
    group: postgres
    mode: 0755
  become: true

- name: "Create backup directory"
  ansible.builtin.file:
    path: "{{ psql_backup_dir }}/{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'
  become: true
  with_items: "{{ postgres_backup_dbs }}"

- name: "Copy systemd service and timer"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/lib/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  become: true
  with_items:
    - postgres-backup@.service
    - postgres-backup@.timer

- name: "Start backup services"
  ansible.builtin.service:
    name: "postgres-backup@{{ item }}.timer"
    state: started
    enabled: true
  become: true
  with_items: "{{ postgres_backup_dbs }}"