[tool.black]
  py310 = true
  line-length = 100
  skip-string-normalization = true

[tool.isort]
    profile = 'black'
    multi_line_output = 3
    line_length = 100
    atomic = true
    skip_gitignore = true
    case_sensitive = true

[tool.mypy]
    junit_xml = '.junit_report.xml'
    follow_imports = 'silent'
    disallow_any_explicit = true
    disallow_any_generics = true
    check_untyped_defs = true
    disallow_untyped_defs = true
    disallow_incomplete_defs = true
    disallow_untyped_decorators = false
    warn_unused_configs = true
    disallow_subclassing_any = true
    disallow_untyped_calls = true
    no_implicit_optional = true
    warn_redundant_casts = true
    warn_unused_ignores = true
    warn_return_any = true
    no_implicit_reexport = true
    show_error_codes = true

[tool.pylint.'MESSAGES CONTROL']
disable = [
    'missing-docstring',
    'too-few-public-methods',
]


[tool.bandit]
# Allow asserts
skips = [
    'B101',
    'B106',
    'B108'
]
