---
- name: Install apt packages
  apt:
    state: present
    name:
      - davfs2
  become: true

- name: "Create config directory"
  file:
    path: "/home/{{ ansible_user_id }}/.davfs2"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
  become: true

- name: "Write secrets"
  copy:
    content: "{{ webdav_path }} {{ webdav_username }} {{ webdav_password }}"
    dest: "/home/{{ ansible_user_id }}/.davfs2/secrets"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0600'
  become: true

- name: Mount nextcloud
  ansible.posix.mount:
    path: "/mnt/cloud-backups"
    src: "https://{{ nextcloud_domain_name }}/remote.php/dav/files/backup/"
    fstype: davfs
    opts: user,rw,noauto,x-systemd.automount,x-systemd.idle-timeout=30
    state: mounted
  environment:
    PATH: "{{ ansible_env.PATH|default('')}}:/usr/local/bin:/usr/bin"
  when: "is_ci|default(False) != True"

- name: "Restart remote-fs"
  ansible.builtin.service:
    name: remote-fs.target
    state: restarted
    enabled: true
  when: ansible_service_mgr == "systemd"
  become: true
  notify: "reload systemd"
