---
- name: Print $PATH
  ansible.builtin.debug:
    msg: "PATH: {{ lookup('ansible.builtin.env', 'PATH', default='') }}"

- name: Upgrade all Packages
  register: updatesys
  apt:
    name: "*"
    state: latest
    update_cache: yes
  become: true

- name: Install apt packages
  apt:
    state: present
    name:
      - wget
      - curl
      - git
      - make
      - unzip
      - tar
      - htop
      - tmux
      - pwgen
      - uidmap
      - telnet
      - aha
      - cargo
      - apt-transport-https
      - wireguard
      - libmagickcore-6.q16-6-extra
      - python3
      - python3-pip
      - python3-psycopg2
      - "{{ extra_common_apt_packages | default('wget') }}"
  become: true

- name: "find all .bashrc files in home directories"
  find:
    paths: /home
    recurse: yes
    file_type: file
    hidden: yes
    pattern: .bashrc
  register: bashrc_files
  tags: "prompt"

# - name: "add bash prompt to all .bashrc files"
#   blockinfile:
#     path: "{{ item.path }}"
#     block: "{{ lookup('file', 'prompt.bash') }}"
#   loop: "{{ bashrc_files.files + [{'path': '/etc/skel/.bashrc'}] }}"
#   loop_control:
#     label: "{{ item.path }}"
#   tags: "prompt"

- name: "set timezone to Europe/Amsterdam"
  timezone:
    name: "Europe/Amsterdam"
  become: true

- name: "ensure en_US.UTF-8 locale is generated"
  locale_gen:
    name: en_US.UTF-8
    state: present
  become: true

- name: "set en_US.UTF-8 locale"  # noqa 301
  command: /usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
  become: true

- name: "Copy get_latest_github_release script"
  ansible.builtin.template:
    src: get_latest_github_release.j2
    dest: /usr/local/bin/get_latest_github_release
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0744
  become: true

- name: Add server to /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {{ wireguard_server.address }} {{ wireguard_server.hostname }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ wireguard_server.hostname }}"
    create: true
  become: true

- name: Add clients to /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {{ item.value.address }} {{ item.key }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.key }}"
  become: true
  loop: "{{ wireguard_clients | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Add server to SSH config
  ansible.builtin.blockinfile:
    path: "/home/{{ username }}/.ssh/config"
    block: |
      Host {{ wireguard_server.address }}
        HostName {{ wireguard_server.hostname }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ wireguard_server.hostname }}"
    create: true
  become: true

- name: Add clients to SSH config
  ansible.builtin.blockinfile:
    path: "/home/{{ username }}/.ssh/config"
    block: |
      Host {{ item.value.address }}
        HostName {{ item.key }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.key }}"
  become: true
  loop: "{{ wireguard_clients | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
