- name: Install apt packages
  apt:
    state: present
    name:
      - postgresql
      - postgresql-contrib
      - postgresql-client
      - pgpdump
  become: true

- ufw:
    state: enabled
    rule: allow
    port: '5432'
    proto: tcp
  become: true

- name: Start postgresql
  ansible.builtin.service:
    name: postgresql
    state: started
  become: true

- name: Allow outside access
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/14/main/postgresql.conf"
    regexp: 'listen_addresses ='
    line: "listen_addresses = '*'"
  become: true

- name: Copy pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/14/main/pg_hba.conf
  become: true

- include: create_db.yml db_name='selfoss' db_user='selfoss' db_pass='{{ selfoss_psql_password }}'
- include: create_db.yml db_name='gitea' db_user='gitea' db_pass='{{ gitea_psql_password }}'
- include: create_db.yml db_name='fr24' db_user='fr24' db_pass='{{ fr24_psql_password }}'
- include: create_db.yml db_name='bracket' db_user='bracket' db_pass='{{ bracket_psql_password }}'
- include: create_db.yml db_name='authelia' db_user='authelia' db_pass='{{ authelia_storage_posgres_password }}'
- include: create_db.yml db_name='grafana' db_user='grafana' db_pass='{{ grafana_psql_password }}'
