---
# These handlers are made available in every play by forcing Ansible to import
# the tasks from this file.
- name: "reload systemd"
  systemd:
    daemon_reload: true
  environment:
    PATH: "{{ ansible_env.PATH|default('')}}:/usr/local/bin:/usr/bin"
  become: true

- name: "Restart gitea"
  block:
    - name: Restart gitea service
      ansible.builtin.service:
        name: gitea
        state: restarted
      listen: "restart gitea"
      become: true
  rescue:
    - name: Run journalctl"
      command: "journalctl -xaeu gitea"
      register: journalctl_gitea_out

    - debug:
        msg: "{{ journalctl_gitea_out.stdout_lines }}"

- name: "reload nginx"
  systemd:
    name: "nginx.service"
    state: "reloaded"
  environment:
    PATH: "{{ ansible_env.PATH|default('')}}:/usr/local/bin:/usr/bin"
  become: true
