---
- ufw:
    state: enabled
    rule: allow
    port: '{{ item }}'
    proto: udp
  with_items:
    - '51820'
    - '51920'
  become: true

- name: Copy wg-cloud conf
  ansible.builtin.template:
    src: "wg-cloud.conf"
    dest: "/etc/wireguard/wg-cloud.conf"
  become: true

- name: Install apt packages
  apt:
    state: present
    name:
      - wireguard
  become: true

- name: Set net.ipv4.ip_forward
  ansible.builtin.lineinfile:
    path: "/etc/sysctl.conf"
    regexp: '^net.ipv4.ip_forward='
    line: "net.ipv4.ip_forward=1"
    create: true
  become: true

- name: Set net.ipv4.conf.all.src_valid_mark
  ansible.builtin.lineinfile:
    path: "/etc/sysctl.conf"
    regexp: '^net.ipv4.conf.all.src_valid_mark='
    line: "net.ipv4.conf.all.src_valid_mark=1"
    create: true
  become: true

- name: "Restart wg-quick services"
  ansible.builtin.service:
    name: '{{ item }}'
    state: restarted
    enabled: true
  become: true
  notify: "reload systemd"
  with_items:
    - 'wg-quick@wg0.service'
    - 'wg-quick@wg-cloud.service'
