server:
  listenaddr: ""
  port: 80

  ssl:
    enabled: false
    letsencrypt:
      enabled: false

database:
  dialect: postgres
  connection: host=${IP_ADDRESS} port=${PSQL_PORT} user=${GOTIFY_PSQL_USER} dbname=${GOTIFY_PSQL_DB} password=${GOTIFY_PSQL_PASSWORD}

defaultuser:
  name: admin
  pass: admin

passstrength: 10
uploadedimagesdir: data/images
pluginsdir: data/plugins
registration: false
