---
- name: Add grafana gpg key
  shell: curl https://packages.grafana.com/gpg.key | apt-key add -
  become: true

- name: Add grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana
  become: true

- name: Install grafana
  apt:
    name:
      - grafana
      - prometheus
      - prometheus-node-exporter
    state: present
    update_cache: yes
  become: true

- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started
  become: true

- name: "Copy Prometheus config"
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: "root"
    group: "root"
    mode: 0644
  become: true
