version: '3.1'

services:
    homeassistant:
        image: homeassistant/home-assistant:stable
        restart: always
        env_file: ~/.env
        volumes:
            - ${HOME_ASSISTANT_DIR}/config:/config
            - /etc/localtime:/etc/localtime
        ports:
            - ${HOME_ASSISTANT_PORT}:${HOME_ASSISTANT_PORT}

    tooljet-client:
        tty: true
        stdin_open: true
        image: tooljet/tooljet-client-ce:latest
        restart: always
        depends_on:
            - tooljet-server
        volumes:
            - logs:/var/log/openresty/
            - certs:/etc/resty-auto-ssl/
            - fallbackcerts:/etc/fallback-certs
        ports:
            - 5001:443
        command: openresty -g "daemon off;"

    tooljet-server:
        image: tooljet/tooljet-server-ce:latest
        tty: true
        stdin_open: true
        restart: always
        ports:
            - 5000
        env_file: .env
        environment:
            RAILS_LOG_TO_STDOUT: "true"
        command: ["bundle", "exec", "rails", "s", "-p", "5000", "-b", "0.0.0.0"]

    mc:
        image: itzg/minecraft-server
        ports:
            - 25565:25565
        environment:
            EULA: "TRUE"
        tty: true
        stdin_open: true
        restart: unless-stopped
        volumes:
            - /var/lib/minecraft-data:/data

    dashy:
        image: lissy93/dashy
        container_name: Dashy
        volumes:
            - /etc/dashy-config.yml:/app/public/conf.yml
        ports:
            - 4000:80
        environment:
            - NODE_ENV=production
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'node', '/app/services/healthcheck']
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s

volumes:
    certs:
    logs:
    fallbackcerts:
