version: '3.1'

services:
    homeassistant:
        image: homeassistant/home-assistant:stable
        restart: always
        env_file: ~/.env
        volumes:
            - ${HOME_ASSISTANT_DIR}/config:/config
            - /etc/localtime:/etc/localtime
        ports:
            - ${HOME_ASSISTANT_PORT}:${HOME_ASSISTANT_PORT}
