---
- name: "Install certificates"
  ansible.builtin.include_tasks: "get-certificates.yml"
  with_items:
    - "{{ certs }}"
  loop_control:
    loop_var: cert

- ufw:
    state: enabled
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - '80'
    - '443'
    - '22'
  become: true
