<?php
$CONFIG = array (
  'instanceid' => '{{ nextcloud_instance_id }}',
  'passwordsalt' => '{{ nextcloud_salt }}',
  'secret' => '{{ nextcloud_secret }}',
  'trusted_domains' =>
  array (
    0 => '{{ nextcloud_domain_name }}',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'pgsql',
  'version' => '22.0.0.11',
  'overwrite.cli.url' => 'https://{{ nextcloud_domain_name }}',
  'dbname' => '{{ nextcloud_psql_db }}',
  'dbhost' => 'localhost:5432',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '{{ nextcloud_psql_user }}',
  'dbpassword' => '{{ nextcloud_psql_password }}',
  'installed' => true,
  'maintenance' => false,
  'mail_from_address' => strtok('{{ email }}', '@'),
  'mail_smtpmode' => 'sendmail',
  'mail_sendmailmode' => 'pipe',
  'mail_domain' => 'gmail.com',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '587',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'updater.secret' => '{{ nextcloud_updater_secret }}',
  'default_phone_region' => 'NL',
);
