<?php
$CONFIG = array (
  'instanceid' => '${NEXTCLOUD_INSTANCE_ID}',
  'passwordsalt' => '${NEXTCLOUD_SALT}',
  'secret' => '${NEXTCLOUD_SECRET}',
  'trusted_domains' =>
  array (
    0 => '${NEXTCLOUD_DOMAIN_NAME}',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'pgsql',
  'version' => '22.0.0.11',
  'overwrite.cli.url' => 'https://${NEXTCLOUD_DOMAIN_NAME}',
  'dbname' => '${NEXTCLOUD_PSQL_DB}',
  'dbhost' => 'localhost:5432',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '${NEXTCLOUD_PSQL_USER}',
  'dbpassword' => '${NEXTCLOUD_PSQL_PASSWORD}',
  'installed' => true,
  'maintenance' => false,
  'mail_from_address' => strtok('${EMAIL}', '@'),
  'mail_smtpmode' => 'sendmail',
  'mail_sendmailmode' => 'pipe',
  'mail_domain' => 'gmail.com',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '587',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'updater.secret' => '${NEXTCLOUD_UPDATER_SECRET}',
  'default_phone_region' => 'NL',
);
