---
- name: Install apt packages
  apt:
    state: present
    name:
      - "{{ php }}"
      - "{{ php }}-gd"
      - "{{ php }}-http"
      - "{{ php }}-curl"
      - "{{ php }}-mbstring"
      - "{{ php }}-tidy"
      - "{{ php }}-imagick"
  become: true

- name: "Get latest Selfoss version"
  shell: "get_latest_github_release --repo 'fossar/selfoss'"
  register: selfoss_version_latest

- name: "Download selfoss"
  ansible.builtin.get_url:
    url: "https://github.com/fossar/selfoss/releases/download/{{ selfoss_version_latest.stdout }}/selfoss-{{ selfoss_version_latest.stdout }}.zip"
    dest: "/tmp/selfoss-{{ selfoss_version_latest.stdout }}"
    force: true
  when: selfoss_version | default(-1) != selfoss_version_latest.stdout

- name: Extract selfoss download
  unarchive:
    remote_src: true
    src: "/tmp/selfoss-{{ selfoss_version_latest.stdout }}"
    dest: /var/www
    owner: www-data
    group: www-data
    mode: 0755
  become: true

- name: "Create data directories"
  file:
    path: "/var/www/selfoss/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 'u=rwX,g=rX,o=rX'
    recurse: true
  with_items:
    - ""
    - "data/cache"
    - "data/favicons"
    - "data/logs"
    - "data/thumbnails"
    - "data/sqlite"
  become: true

- name: "Copy config"
  ansible.builtin.template:
    src: config.ini.j2
    dest: /var/www/selfoss/config.ini
    owner: "www-data"
    group: "www-data"
    mode: 0644
  become: true

- name: Update selfoss version
  ansible.builtin.lineinfile:
    path: "{{ concordia_dir }}/ansible/installed_versions.yml"
    regexp: '^selfoss_version:'
    line: "selfoss_version: {{ selfoss_version_latest.stdout }}"

- name: "Create selfoss-discord directory"
  file:
    path: "/var/lib/selfoss-discord"
    state: directory
    owner: www-data
    group: www-data
    mode: 'u=rwX,g=rX,o=rX'
    recurse: true
  become: true

- name: "Get latest selfoss-discord version"
  shell: "get_latest_github_release --repo 'evroon/selfoss-discord'"
  register: selfoss_discord_version_latest

- name: "Download selfoss-discord"
  ansible.builtin.get_url:
    url: "https://github.com/evroon/selfoss-discord/releases/download/{{ selfoss_discord_version_latest.stdout }}/selfoss-discord"
    dest: "/var/lib/selfoss-discord/selfoss-discord"
    owner: www-data
    group: www-data
    mode: 0700
    force: true
  become: true

- name: "Copy .env script"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/var/lib/selfoss-discord/{{ item }}"
    owner: "www-data"
    group: "www-data"
    mode: 0700
  become: true
  with_items:
    - .env

- name: "Copy systemd service and timer"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/lib/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  become: true
  with_items:
    - selfoss-update.service
    - selfoss-update.timer

- name: "Start selfoss-update service"
  ansible.builtin.service:
    name: "selfoss-update.timer"
    state: started
    enabled: true
  become: true
