---
- name: Install apt packages
  apt:
    state: present
    name:
      - ufw
      - iptables
  become: true

- ufw:
    state: enabled
    rule: allow
    port: '22'
    proto: tcp
  become: true

- name: "Set legacy iptables version on rpi"
  command: "update-alternatives --set iptables /usr/sbin/iptables-legacy"
  become: true
  when: inventory_hostname == 'pi'

- ufw:
    state: enabled
    rule: allow
    proto: tcp
    from_ip: '{{ item }}'
  with_items:
    - "{{ lookup('dig', '{{ domain_name }}') }}"
    - "192.168.1.0/24"
    - "10.8.1.0/24"
  become: true
