---
- ufw:
    state: enabled
    rule: allow
    port: '{{ item }}'
    proto: udp
  with_items:
    - '51820'
  become: true

- name: Install apt packages
  apt:
    state: present
    name:
      - wireguard
  become: true

- name: Set net.ipv4.ip_forward
  ansible.builtin.lineinfile:
    path: "/etc/sysctl.conf"
    regexp: '^net.ipv4.ip_forward='
    line: "net.ipv4.ip_forward=1"
    create: true
  become: true

- name: Set net.ipv4.conf.all.src_valid_mark
  ansible.builtin.lineinfile:
    path: "/etc/sysctl.conf"
    regexp: '^net.ipv4.conf.all.src_valid_mark='
    line: "net.ipv4.conf.all.src_valid_mark=1"
    create: true
  become: true

- name: "Setup dummy wg0.conf for CI only"
  ansible.builtin.template:
    src: ci-wg0.conf
    dest: /etc/wireguard/wg0.conf
    owner: "root"
    group: "root"
    mode: 0600
  become: true
  when: "is_ci|default(False) == true"

- name: "Service wg-quick@wg0"
  ansible.builtin.service:
    name: wg-quick@wg0
    state: started
    enabled: true
  become: true
