---
- ufw:
    state: enabled
    rule: allow
    port: '{{ item }}'
    proto: udp
  with_items:
    - '51820'
  become: true

- name: Install apt packages
  apt:
    state: present
    name:
      - wireguard
  become: true

- name: Set net.ipv4.ip_forward
  ansible.builtin.lineinfile:
    path: "/etc/sysctl.conf"
    regexp: '^net.ipv4.ip_forward='
    line: "net.ipv4.ip_forward=1"
    create: true
  become: true

- name: Set net.ipv4.conf.all.src_valid_mark
  ansible.builtin.lineinfile:
    path: "/etc/sysctl.conf"
    regexp: '^net.ipv4.conf.all.src_valid_mark='
    line: "net.ipv4.conf.all.src_valid_mark=1"
    create: true
  become: true

- name: "Setup dummy wg1.conf for CI only"
  ansible.builtin.template:
    src: ci-wg1.conf
    dest: /etc/wireguard/wg1.conf
    owner: "root"
    group: "root"
    mode: 0600
  become: true
  when: "is_ci|default(false) == true"

- name: "Start wg-quick"
  block:
  - name: "Service wg-quick@wg1"
    ansible.builtin.service:
      name: wg-quick@wg1
      state: started
      enabled: true
    become: true
  rescue:
  - name: get errors
    shell: journalctl -xeu wg-quick@wg1
    register: err_msg
    become: true
  - name: Print error message to console
    debug:
      msg: "{{ err_msg.stdout }}"
