---
- name: Copy directory-backup executable
  ansible.builtin.template:
    src: directory-backup.j2
    dest: /usr/local/bin/directory-backup
    owner: {{ ansible_user_id }}
    group: {{ ansible_user_id }}
    mode: 0755
  become: true

- name: "Create backup directory"
  ansible.builtin.file:
    path: "{{ psql_backup_dir }}/{{ item }}/{{ ansible_hostname }}"
    state: directory
    owner: {{ ansible_user_id }}
    group: {{ ansible_user_id }}
    mode: '0755'
  become: true
  with_items: "{{ directory_backup_dbs }}"

- name: "Copy systemd service and timer"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/lib/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  become: true
  with_items:
    - directory-backup@.service
    - directory-backup@.timer

- name: "Start backup services"
  ansible.builtin.service:
    name: "directory-backup@{{ item }}.timer"
    state: started
    enabled: true
  become: true
  with_items: "{{ directory_backup_dbs }}"