---
- name: Install apt packages
  apt:
    state: present
    name:
      - nginx
  become: true

- ufw:
    state: enabled
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - '80'
    - '443'
    - '22'
  become: true

- name: Uninstall apache2
  apt:
    state: absent
    name:
      - apache2
  become: true

- name: Copy nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true
  notify: "reload nginx"

- name: "Install certificates"
  ansible.builtin.include_tasks: "get-certificates.yml"
  with_items:
    - "{{ certs }}"
  loop_control:
    loop_var: cert
