---
- name: Install apt packages
  apt:
    state: present
    name:
      - nginx
  become: true

- name: Uninstall apache2
  apt:
    state: absent
    name:
      - apache2
  become: true

- name: Copy nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true
  notify: "reload nginx"
