---
- name: Install apt packages
  apt:
    state: present
    name:
      - docker-compose
  become: true

- name: Copy scripts
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
  become: true
  with_items:
    - "restart-docker-services.sh"

- name: "Create docker-compose directory"
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
  become: true

- name: "Copy docker-compose.yml"
  ansible.builtin.template:
    src: "docker-compose/{{ group_names | first }}.yml.j2"
    dest: "{{ docker_compose_dir }}/docker-compose.yml"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'
  become: true

- name: "Copy .env"
  ansible.builtin.template:
    src: ".env.j2"
    dest: "{{ docker_compose_dir }}/.env"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'
  become: true

- name: Create and start Docker services
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}"
  become: true
