---
- name: Install apt packages
  apt:
    state: present
    name:
      - docker-compose
  become: true

- name: Copy scripts
  ansible.builtin.template:
    src: "scripts/{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
    remote_src: true
  become: true
  with_items:
    - "restart-docker-services.sh"
    - "start-docker-services.sh"

- name: "Create directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
  with_items:
    - "{{ docker_compose_dir }}"
  become: true

- name: "Create volume directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "10001"
    group: "10001"
    mode: '0755'
  with_items:
    - "{{ docker_compose_dir }}/volumes/loki"
  become: true

- name: "Copy .env"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ docker_compose_dir }}/{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'
  with_items:
    - ".env"
  become: true

- name: "Copy docker-compose.yml"
  ansible.builtin.template:
    src: "docker-compose/{{ item }}.yml.j2"
    dest: "{{ docker_compose_dir }}/docker-compose.yml"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'
  with_items:
    - "{{ group_names }}"
  become: true

- name: Run docker-compose up -d
  shell: start-docker-services.sh
