---
- name: Playbook to build concordia
  hosts: webserver
  tasks:
    - include_vars: inventory.yml
    - include_vars: installed_versions.yml
    - include_vars: secrets.enc
    - include: setup.yml
    - include: install-requirements.yml
    - include: ufw.yml
    - include: install-files.yml
    - include: postgres.yml
    - include: btop.yml
    - include: munin.yml
    - include: selfoss.yml
    - include: redis.yml
    - include: nextcloud.yml
    - include: gitea.yml
    - include: nginx/nginx.yml

  handlers:
  - name: Restart gitea
    ansible.builtin.service:
      name: gitea
      state: restarted
    listen: "restart gitea"

  - name: Reload nginx
    include_tasks: nginx/reload-nginx.yml
    listen: "restart nginx"

  - name: Restart php-fpm
    ansible.builtin.service:
      name: php{{ php_version }}-fpm
      state: restarted
    listen: "restart php-fpm"

  - name: Restart redis-server
    ansible.builtin.service:
      name: redis-server
      state: restarted
    listen: "restart redis-server"
