---
- name: Playbook to build concordia
  hosts: localhost
  connection: local
  tasks:
    - include: install-requirements.yml
    - include: setup.yml
    - include: ufw.yml
    - include: install-files.yml
    - include: postgres.yml
    - include: munin.yml
    - include: selfoss.yml
    - include: nextcloud.yml
    - include: gitea.yml
    - include: nginx/nginx.yml

  handlers:
  - name: Restart gitea
    ansible.builtin.service:
      name: gitea
      state: restarted
    listen: "restart gitea"

  - name: Restart nginx
    include_tasks: nginx/reload-nginx.yml
    listen: "restart nginx"
