#!/usr/bin/ansible-playbook -e @secrets.enc

---
- name: Install user packages
  hosts: localhost
  connection: localhost
  tasks:
    - include: install-files.yml
    # - include: nextcloud.yml
    # - include: gitea.yml
    # - include: munin.yml
    # - include: selfoss.yml
