---
- name: Move /usr/bin files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/bin
    mode: '0755'
  with_fileglob:
    - ../usr/bin/*
  become: yes

- name: Move systemd service files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /lib/systemd/system
    mode: '0755'
  with_fileglob:
    - ../lib/systemd/system/*
  become: yes

- stat: path=/nix
  register: nix_dir

- block:
  - name: Create /nix
    ansible.builtin.file:
      path: /nix
      state: directory
      mode: '0777'
      owner: "{{ username }}"
      group: "{{ username }}"
    become: yes

  - name: Install nix
    command: "nix-install.sh"
    become: true
    become_user: "{{ username }}"
  when: not (nix_dir.stat.isdir is defined and nix_dir.stat.isdir)
