php_version: 8.1
php: "php{{ php_version }}"

authelia:
  secrets:
    - jwt_secret:
      filename: jwt_secret
      secret: "{{ authelia_jwt_secret }}"
    - session_secret:
      filename: session_secret
      secret: "{{ authelia_session_secret }}"
    - posgres_password:
      filename: posgres_password
      secret: "{{ authelia_storage_posgres_password }}"
    - encryption_key:
      filename: encryption_key
      secret: "{{ authelia_storage_encryption_key }}"
