- hosts: dmz
  handlers:
    - import_tasks: "roles/common/handlers/main.yml"
  roles:
    - role: "common"
    - role: "1password"
    - role: "redis"
    - role: "authelia"
    - role: "davfs2"
    - role: "grafana"
    - role: "restic-backup"
    - role: "docker"
    - role: "email"
    - role: "fail2ban"
    - role: "promtail"
    - role: "homedir"
    - role: "letsencrypt"
    - role: "munin"
    - role: "nomad"
    - role: "nginx"
    - role: "nginx-dmz"
    - role: "nix"
    - role: "postgres"
    - role: "node-exporter"
    - role: "selfoss"
    - role: "sshd"
    - role: "systemd"
    - role: "ufw"
    - role: "unattended_upgrades"
    - role: "gitea"
    - role: "bracket"
    - role: "wireguard-server"

- hosts: dev_machines
  handlers:
    - import_tasks: "roles/common/handlers/main.yml"
  roles:
    - role: "common"
    - role: "homedir"
    - role: "unattended_upgrades"

- hosts: pis
  handlers:
    - import_tasks: "roles/common/handlers/main.yml"
  roles:
    - role: "common"
    - role: "adsb"
    - role: "email"
    - role: "fail2ban"
    - role: "promtail"
    - role: "node-exporter"
    - role: "homedir"
    - role: "sshd"
    - role: "ufw"
    - role: "nginx"
    - role: "nginx-prometheus-proxy"
    - role: "docker"
    - role: "unattended_upgrades"
    - role: "wireguard-client"

- hosts: vpn_pis
  handlers:
    - import_tasks: "roles/common/handlers/main.yml"
  roles:
    - role: "common"
    - role: "fail2ban"
    - role: "node-exporter"
    - role: "docker"
    - role: "promtail"
    - role: "homedir"
    - role: "sshd"
    - role: "ufw"
    - role: "unattended_upgrades"
    - role: "wireguard-client"

- hosts: restricted
  handlers:
    - import_tasks: "roles/common/handlers/main.yml"
  roles:
    - role: "common"
    - role: "fail2ban"
    - role: "node-exporter"
    - role: "postgres"
    - role: "promtail"
    - role: "sshd"
    - role: "ufw"
