- hosts: webservers
  handlers:
    - import_tasks: "roles/common/handlers/main.yml"
  roles:
    - role: "common"
    - role: "1password"
    - role: "authelia"
    - role: "davfs2"
    - role: "grafana"
    - role: "docker"
    - role: "email"
    - role: "fail2ban"
    - role: "promtail"
    - role: "homedir"
    - role: "letsencrypt"
    - role: "munin"
    - role: "nginx"
    - role: "nix"
    - role: "postgres"
    - role: "node-exporter"
    - role: "selfoss"
    - role: "sshd"
    - role: "systemd"
    - role: "ufw"
    - role: "unattended_upgrades"
    - role: "gitea"
    - role: "bracket"
<<<<<<< Updated upstream
    - role: "wireguard"
=======
    - role: "wireguard-server"
    - role: "restic-backup"
>>>>>>> Stashed changes

- hosts: dev_machines
  handlers:
    - import_tasks: "roles/common/handlers/main.yml"
  roles:
    - role: "common"
    - role: "homedir"
    - role: "unattended_upgrades"

- hosts: pis
  handlers:
    - import_tasks: "roles/common/handlers/main.yml"
  roles:
    - role: "common"
    - role: "adsb"
    - role: "email"
    - role: "fail2ban"
    - role: "promtail"
    - role: "node-exporter"
    - role: "homedir"
    - role: "sshd"
    - role: "ufw"
    - role: "unattended_upgrades"

- hosts: vpn_pis
  handlers:
    - import_tasks: "roles/common/handlers/main.yml"
  roles:
    - role: "common"
    - role: "fail2ban"
    - role: "node-exporter"
    - role: "promtail"
    - role: "homedir"
    - role: "sshd"
    - role: "ufw"
    - role: "unattended_upgrades"
