---

- name: "Get latest Selfoss version"
  shell: "get_latest_github_release --repo 'fossar/selfoss'"
  register: selfoss_version_latest

- name: "Download selfoss"
  ansible.builtin.get_url:
    url: "https://github.com/fossar/selfoss/releases/download/{{ selfoss_version_latest.stdout }}/selfoss-{{ selfoss_version_latest.stdout }}.zip"
    dest: /var/www/selfoss
    owner: www-data
    group: www-data
    mode: 0755
    force: true
  when: selfoss_version | default(-1) != selfoss_version_latest.stdout

- name: Git clone selfoss-discord
  git:
    repo: 'https://github.com/evroon/selfoss-discord'
    dest: "/var/lib/discord"
  become_user: www-data

- name: Update selfoss version
  ansible.builtin.lineinfile:
    path: "{{ CONCORDIA_DIR }}/ansible/installed_versions.yml"
    regexp: '^selfoss_version:'
    line: "selfoss_version: {{ selfoss_version_latest.stdout }}"

- name: "Copy update script"
  ansible.builtin.template:
    src: ../usr/bin/update-selfoss.j2
    dest: /usr/bin/selfoss-update
    owner: "www-data"
    group: "www-data"
    mode: 0700
