---
- name: Ansible Update Cache and Upgrade all Packages
  register: updatesys
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install apt packages
  apt:
    state: present
    name:
      - wget
      - curl
      - python3
      - python3-pip
      - git
      - make
      - htop
      - tmux
      - pwgen
      - uidmap
      - telnet
      - munin
      - libcgi-fast-perl
      - postgresql
      - postgresql-contrib
      - postgresql-client
      - pgpdump
      - "{{ php }}"
      - "{{ php }}-gd"
      - "{{ php }}-mbstring"
      - "{{ php }}-common"
      - "{{ php }}-pgsql"
      - "{{ php }}-imagick"
      - "{{ php }}-xml"
      - "{{ php }}-curl"
      - "{{ php }}-tidy"
      - "{{ php }}-zip"
      - "{{ php }}-fpm"
      - "{{ php }}-intl"
      - "{{ php }}-bcmath"
      - "{{ php }}-gmp"
      - certbot
      - python3-certbot-nginx
      - mailutils
      - msmtp
      - msmtp-mta
      - aha
      - unzip
      - docker-compose
      - prometheus
      - prometheus-node-exporter
      - apt-transport-https
      - fail2ban
      - wireguard

- name: Uninstall apache2
  apt:
    state: absent
    name:
      - apache2

- name: Start postgresql
  ansible.builtin.service:
    name: postgresql
    state: started

- name: Add grafana gpg key
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: Add grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Install grafana
  apt:
      name: grafana
      state: present
      update_cache: yes

- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started

- name: Install python dependencies
  command: pip3 install python-dateutil psycopg2
  become: true

- include: user.yml
