#!/usr/bin/env python3

import sys
import json
import requests

def print_config() -> None:
    print("graph_title FR24 aircraft")
    print("graph_vlabel aircraft")
    print("graph_args --upper-limit 20 -l 0")
    print("graph_category fr24")
    print("graph_info Number of aircraft detected by ADS-B receiver.")

    for domain in domains:
        print("{0}.label {0}.nl".format(domain))


def print_value() -> None:
    response = requests.get('${FR24_ADDRESS}')
    if response.ok:
        data = json.loads(response.content)
        num_aircraft = len(data)
        print(f'fr24.value {num_aircraft}')


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'config':
        print_config()
    else:
        print_value()
