# See: https://gist.github.com/stevenvandervalk/130cba3488611d44390738dd86bb2ea5

# Use a 4096 bit RSA key instead of 2048.
rsa-key-size = 4096
# Set email and domains.
email = {{ email }}
domains = {{ domain_name }},www.{{ domain_name }},{{ gitea_domain_name }},{{ selfoss_domain_name }},{{ munin_domain_name }},{{ nextcloud_domain_name }},{{ web1090_domain_name}},{{ web1090_api_domain_name }},{{ uptime_kuma_domain_name }},{{ gotify_domain_name }},{{ grafana_domain_name }}
# Text interface.
text = True
# No prompts.
non-interactive = True
# Suppress the Terms of Service agreement interaction.
agree-tos = True
# Use the webroot authenticator.
authenticator = webroot
webroot-path = /var/www/html
