---
- name: Install apt packages
  apt:
    state: present
    name:
      - munin
  become: true

- stat:
    path: /etc/munin/static
  register: static_dir

- block:
  - name: Create /etc/munin if it does not exist
    ansible.builtin.file:
      path: /etc/munin
      state: directory
      mode: '0755'

  - name: Create /usr/share/munin if it does not exist
    ansible.builtin.file:
      path: /usr/share/munin
      state: directory
      mode: '0755'

  - name: Copy munin-node
    ansible.builtin.copy:
      src: ../munin/munin-node
      dest: /etc/munin/munin-node

  - name: Copy munin.conf
    ansible.builtin.copy:
      src: ../munin/munin.conf
      dest: /etc/munin/munin.conf

  - name: Copy plugins
    ansible.builtin.copy:
      src: ../munin/plugins
      dest: /usr/share/munin/plugins

  - name: Create temporary template directory
    ansible.builtin.tempfile:
      state: directory
      suffix: munin-contrib
    register: munin_contrib_tmp_dir

  - name: Git clone contrib
    ansible.builtin.git:
      repo: 'https://github.com/munin-monitoring/contrib.git'
      dest: "{{ munin_contrib_tmp_dir.path }}"
    environment:
      PATH: "{{ ansible_env.PATH|default('')}}:/usr/local/bin:/usr/bin"

  - name: Copy templates
    ansible.builtin.copy:
      src: "{{ munin_contrib_tmp_dir.path }}/templates/munstrap/templates"
      dest: /etc/munin

  - name: Copy static
    ansible.builtin.copy:
      src: "{{ munin_contrib_tmp_dir.path }}/templates/munstrap/static"
      dest: /etc/munin

  - name: Let Munin regenerate HTML files
    file:
      state: absent
      path: /var/www/munin/*
  when: not (static_dir.stat.isdir is defined and static_dir.stat.isdir)

# - name: Create symlinks for plugins
#   ansible.builtin.file:
#     src: "{{ item }}"
#     dest: /usr/bin
#     mode: '0744'
#     state: link
#   with_fileglob:
#     -

# - name: Create symlinks for plugins
#   ansible.builtin.file:
#     src: "{{ item }}"
#     dest: /usr/bin
#     mode: '0744'
#     state: link
#   with_fileglob:
#     - /etc/munin/plugins/*
