name: ansible

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install ansible
        run: sudo apt install ansible && sudo ansible-galaxy collection install community.postgresql

      - name: Run ansible playbooks
        run: sudo ansible-playbook -e @ansible/secrets.ci.yml -e @ansible/inventory.yml -e @ansible/installed_versions.yml ansible/build.yml
